import { Headphones, CreditCard, Smartphone } from "lucide-react";

export const content = {
  register: {
    title: "Comece agora o seu teste grátis",
    description:
      "Com a ADAP todo o seu financeiro fica organizado, de forma automática, bem na palma da sua mão.",
    features: [
      {
        icon: Smartphone,
        title: "Na palma da sua mão",
        description: "Lance todos os seus gastos direto do WhatsApp em menos de 5 segundos.",
      },
      {
        icon: Headphones,
        title: "Suporte Especializado e humanizado",
        description: "Suporte 100% humanizado para te guiar em qualquer dúvida.",
      },
      {
        icon: CreditCard,
        title: "Sem cobranças inesperadas",
        description: "Comece seu teste sem precisar cadastrar cartão.",
      },
    ],
    ctaText: "*planos superiores ou contratação à parte",
    form_title: "Seja um Adaptado(a)",
    form_description: "Coloque o seu financeiro no piloto automático para focar no que realmente importa.",
    segmentOptions: [
      { value: "Comércio (e-commerce)", label: "Comércio (e-commerce)" },
      { value: "Comércio (loja física)", label: "Comércio (loja física)" },
      { value: "Indústria", label: "Indústria" },
      { value: "Serviços", label: "Serviços" },
    ],
    mainActivityOptions: [
      { value: "Agronegócio", label: "Agronegócio" },
      { value: "Alimentos e bebidas", label: "Alimentos e bebidas" },
      { value: "Arte", label: "Arte" },
      { value: "Artesanato", label: "Artesanato" },
      { value: "Artigos esportivos", label: "Artigos esportivos" },
      { value: "Artigos para bebês", label: "Artigos para bebês" },
      { value: "Bares e restaurantes", label: "Bares e restaurantes" },
      { value: "Beleza, perfumaria e medicamentos", label: "Beleza, perfumaria e medicamentos" },
      { value: "Brinquedos", label: "Brinquedos" },
      { value: "Clubes e associações", label: "Clubes e associações" },
      { value: "Comunicação e telecomunicação", label: "Comunicação e telecomunicação" },
      { value: "Computadores e internet", label: "Computadores e internet" },
      { value: "Consoles e Video-Games", label: "Consoles e Video-Games" },
      { value: "Delivery", label: "Delivery" },
      { value: "Decoração", label: "Decoração" },
      { value: "Eletro-eletrônicos", label: "Eletro-eletrônicos" },
      { value: "Eletroportáteis", label: "Eletroportáteis" },
      { value: "Energia elétrica", label: "Energia elétrica" },
      { value: "Educação", label: "Educação" },
      { value: "Ferragens", label: "Ferragens" },
      { value: "Financeiro, contábil, jurídico", label: "Financeiro, contábil, jurídico" },
      { value: "Higiene e limpeza", label: "Higiene e limpeza" },
      { value: "Imóveis e construção", label: "Imóveis e construção" },
      { value: "Jóias e óticas", label: "Jóias e óticas" },
      { value: "Máquinas e equipamentos", label: "Máquinas e equipamentos" },
      { value: "Moda e acessórios", label: "Moda e acessórios" },
      { value: "Móveis, casa e decoração", label: "Móveis, casa e decoração" },
      { value: "ONGs", label: "ONGs" },
      { value: "Pet", label: "Pet" },
      { value: "Propaganda e comunicação", label: "Propaganda e comunicação" },
      { value: "Saúde e medicina", label: "Saúde e medicina" },
      { value: "Segurança", label: "Segurança" },
      { value: "Smartphones", label: "Smartphones" },
      { value: "Veiculos e peças", label: "Veiculos e peças" },
      { value: "Outros", label: "Outros" },
    ],
  },
  login: {
    form_title: "Bem vindo de volta!",
    form_description: "Organize suas finanças de maneira mais completa e profissional",
  },
};
